source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'JCNetworkKit_Example' do
  pod 'JCNetworkKit', :path => '../'
  pod 'AFNetworking', '~> 3.0'
  pod 'MBProgressHUD', '~> 1.1.0'

  target 'JCNetworkKit_Tests' do
    inherit! :search_paths
    
  end
end
